### PR TITLE
Optional registration against node.js 'module'

### PR DESCRIPTION
**Pull request by massar**
This allows using punycode.js directly without node.js

### CODE REVIEW

**Comment by mathiasbynens** [comment]
How is this different from https://github.com/bestiejs/punycode.js/pull/61?

**Comment by massar** [comment]
It is not per-se different. It just updates the comment that it is against NodeJS, as I previously mistakingly thought it was jQuery.

Same trick though: check if "module" exists, if not, don't try to use it.

**Comment by mathiasbynens** [comment]
I understand the code change. Did you read https://github.com/bestiejs/punycode.js/pull/61#issuecomment-285095954, i.e. why don’t you just use the older version of Punycode.js in situations where browser support is desired?

**Comment by massar** [comment]
Yes, saw that (and that Firefox 48 is borked), but it works fine under all current browsers; the only thing one will see is that 'module' is unreferenced when using it directly like is, hence the patch.

**Comment by mathiasbynens** [comment]
It’s not a goal of the project to support browsers, currently.

**Comment by massar** [comment]
No worries, that is what forks are for.

**Comment by mathiasbynens** [comment]
I still don’t see why you want to do this — why not just use the version of Punycode.js with browser support?

**Pull request closed without merging**
