### PR TITLE
Bump bower version

### LINKED ISSUE #43: version 1.4 not available in bower
seems the bower.json is outdated.

### PR DESCRIPTION
**Pull request by XzAeRo**
Fixes #43

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Thanks! I just amended and retagged v1.4.0: 373a53ca002e5d25d3b1cec79fbabae970f557f4

**Comment by XzAeRo** [comment]
I just noticed that component.json also is set to 1.3.2

**Comment by mathiasbynens** [comment]
Thanks again, @XzAeRo! Fixed. (I should really remove these files for the next update…)

**Comment by XzAeRo** [comment]
Haha, you're welcome!

**Pull request closed without merging**
